// Code generated by gen_i18n. DO NOT EDIT.
package i18n

type Language struct {
	Code string
	Name string
}

var SupportedLanguages = []Language{
	{Code: "en", Name: "English"},
	{Code: "de", Name: "Deutsch"},
	{Code: "es", Name: "Español"},
	{Code: "fr", Name: "Français"},
	{Code: "it", Name: "Italiano"},
	{Code: "ja", Name: "日本語"},
	{Code: "pt", Name: "Português"},
	{Code: "ru", Name: "Русский"},
	{Code: "uk", Name: "Українська"},
	{Code: "zh", Name: "简体中文"},
	{Code: "zh-Hant", Name: "繁體中文"},
}

func GetLanguageNames() []string {
	names := []string{"System Default"}
	for _, lang := range SupportedLanguages {
		names = append(names, lang.Name)
	}
	return names
}
