package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Language struct {
	Code string
	Name string
}

func main() {
	translationsDir := "pkg/i18n/translations"
	outputFile := "pkg/i18n/zz_generated_languages.go"

	// If we are running inside pkg/i18n (e.g. via go generate), adjust the paths
	if _, err := os.Stat("translations"); err == nil {
		translationsDir = "translations"
		outputFile = "zz_generated_languages.go"
	}

	files, err := os.ReadDir(translationsDir)
	if err != nil {
		log.Fatalf("failed to read translations dir (%s): %v", translationsDir, err)
	}

	// 1. Load en.json first as the reference
	enPath := filepath.Join(translationsDir, "en.json")
	enData, err := os.ReadFile(enPath)
	if err != nil {
		log.Fatalf("failed to read %s: %v", enPath, err)
	}

	var enMap map[string]interface{}
	if err := json.Unmarshal(enData, &enMap); err != nil {
		log.Fatalf("failed to unmarshal %s: %v", enPath, err)
	}

	// Calculate counts for logging
	metaName := enMap["_meta_name"]
	delete(enMap, "_meta_name")
	enKeyCount := len(enMap)
	fmt.Printf("Reference en.json loaded with %d keys\n", enKeyCount)

	// Rewrite en.json immediately to guarantee alphabetical sorting
	if metaName != nil {
		enMap["_meta_name"] = metaName
	}
	if enOut, err := json.MarshalIndent(enMap, "", "  "); err == nil {
		if writeErr := os.WriteFile(enPath, enOut, 0600); writeErr != nil {
			log.Printf("warning: failed to write %s: %v", enPath, writeErr)
		}
	}
	delete(enMap, "_meta_name")

	// 2. Generate pseudo.json
	pseudoMap := make(map[string]string)
	pseudoMap["_meta_name"] = "[!! Pseudo-Loc !!]"
	for k, v := range enMap {
		if str, ok := v.(string); ok {
			pseudoMap[k] = pseudolocalize(str)
		}
	}

	pseudoPath := filepath.Join(translationsDir, "pseudo.json")
	pseudoData, err := json.MarshalIndent(pseudoMap, "", "  ")
	if err != nil {
		log.Fatalf("failed to marshal pseudo.json: %v", err)
	}
	if err := os.WriteFile(pseudoPath, pseudoData, 0600); err != nil {
		log.Fatalf("failed to write pseudo.json: %v", err)
	}
	fmt.Println("Generated pseudo.json for layout testing")

	var languages []Language
	for _, f := range files {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}

		code := strings.TrimSuffix(f.Name(), ".json")
		if code == "pseudo" {
			continue
		}
		path := filepath.Join(translationsDir, f.Name())

		data, err := os.ReadFile(path)
		if err != nil {
			log.Printf("warning: failed to read %s: %v", path, err)
			continue
		}

		var m map[string]interface{}
		if err := json.Unmarshal(data, &m); err != nil {
			log.Printf("warning: failed to unmarshal %s: %v", path, err)
			continue
		}

		name, ok := m["_meta_name"].(string)
		if !ok {
			log.Printf("warning: %s missing _meta_name", path)
			continue
		}

		// Auto-fill any missing keys from en.json
		changed := false
		for k, v := range enMap {
			if _, ok := m[k]; !ok {
				m[k] = v
				changed = true
			}
		}

		if changed {
			log.Printf("info: auto-filled missing keys in %s.json", code)
		}

		// Always rewrite the file to guarantee alphabetical sorting
		if outData, err := json.MarshalIndent(m, "", "  "); err == nil {
			if writeErr := os.WriteFile(path, outData, 0600); writeErr != nil {
				log.Printf("warning: failed to write %s: %v", path, writeErr)
			}
		} else {
			log.Printf("warning: failed to rewrite %s: %v", path, err)
		}

		languages = append(languages, Language{
			Code: code,
			Name: name,
		})
	}

	// Sort languages by code for deterministic output, but keep English first if it exists
	sort.Slice(languages, func(i, j int) bool {
		if languages[i].Code == "en" {
			return true
		}
		if languages[j].Code == "en" {
			return false
		}
		return languages[i].Code < languages[j].Code
	})

	f, err := os.Create(outputFile)
	if err != nil {
		log.Fatalf("failed to create output file: %v", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by gen_i18n. DO NOT EDIT.")
	fmt.Fprintln(f, "package i18n")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "type Language struct {")
	fmt.Fprintln(f, "	Code string")
	fmt.Fprintln(f, "	Name string")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "var SupportedLanguages = []Language{")
	for _, lang := range languages {
		fmt.Fprintf(f, "	{Code: %q, Name: %q},\n", lang.Code, lang.Name)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "func GetLanguageNames() []string {")
	fmt.Fprintln(f, "	names := []string{\"System Default\"}")
	fmt.Fprintln(f, "	for _, lang := range SupportedLanguages {")
	fmt.Fprintln(f, "		names = append(names, lang.Name)")
	fmt.Fprintln(f, "	}")
	fmt.Fprintln(f, "	return names")
	fmt.Fprintln(f, "}")

	// 5. Generate zz_generated_pseudoloc.go
	pseudoFile := "pkg/i18n/zz_generated_pseudoloc.go"
	if _, err := os.Stat("translations"); err == nil {
		pseudoFile = "zz_generated_pseudoloc.go"
	}

	pf, err := os.Create(pseudoFile)
	if err != nil {
		log.Fatalf("failed to create %s: %v", pseudoFile, err)
	}
	defer pf.Close()

	fmt.Fprintln(pf, "// Code generated by gen_i18n. DO NOT EDIT.")
	fmt.Fprintln(pf, "//go:build !release")
	fmt.Fprintln(pf)
	fmt.Fprintln(pf, "package i18n")
	fmt.Fprintln(pf)
	fmt.Fprintln(pf, "func init() {")
	fmt.Fprintln(pf, "	SupportedLanguages = append(SupportedLanguages, Language{Code: \"pseudo\", Name: \"[!! Pseudo-Loc !!]\"})")
	fmt.Fprintln(pf, "}")
}

func normalize(s string) string {
	s = strings.ReplaceAll(s, " ", "")
	s = strings.ReplaceAll(s, "\t", "")
	s = strings.ReplaceAll(s, "\n", "")
	s = strings.ReplaceAll(s, "\r", "")
	return strings.ToLower(s)
}

func pseudolocalize(s string) string {
	var sb strings.Builder
	sb.WriteString("[!! ")

	inPlaceholder := false
	for i := 0; i < len(s); i++ {
		char := s[i]
		if char == '{' && i+1 < len(s) && s[i+1] == '{' {
			inPlaceholder = true
		}
		if char == '}' && i-1 >= 0 && s[i-1] == '}' {
			inPlaceholder = false
		}

		sb.WriteByte(char)

		if !inPlaceholder {
			// Double vowels to expand string
			if strings.ContainsRune("aeiouAEIOU", rune(char)) {
				sb.WriteByte(char)
			}
		}
	}

	sb.WriteString(" !!]")
	return sb.String()
}
