run:
  timeout: 15m
  concurrency: 1
  modules-download-mode: readonly
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - gosec

linters-settings:
  staticcheck:
    checks: ["all"]
