import json
import os

# Comprehensive UI translations for Spice Providers
translations = {
    "de": {
        "(Token Expired)": "(Token abgelaufen)",
        "Downloading %d items...": "Herunterladen von %d Elementen...",
        "Error: ": "Fehler: ",
        "Collection %s (%d items)": "Sammlung %s (%d Elemente)",
        "Enter your Pexels API Key": "Pexels-API-Schlüssel eingeben",
        "Pexels API Key:": "Pexels-API-Schlüssel:",
        "Invalid API Key format (56 characters)": "Ungültiges API-Schlüssel-Format (56 Zeichen)",
        "New Pexels Query": "Neue Pexels-Abfrage",
        "Invalid Pexels URL (search or collection)": "Ungültige Pexels-URL (Suche oder Sammlung)",
        "duplicate query: this URL already exists": "Doppelte Abfrage: Diese URL existiert bereits",
        "Pexels Queries": "Pexels-Abfragen",
        "Manage your Pexels image queries here.": "Verwalten Sie hier Ihre Pexels-Bildabfragen.",
        "API Key required for verification": "API-Schlüssel zur Verifizierung erforderlich",
        "New Image Query": "Neue Bildabfrage",
        "Invalid wallhaven image query URL pattern": "Ungültiges Wallhaven-Bildabfrage-URL-Muster",
        "Duplicate query: this URL already exists": "Doppelte Abfrage: Diese URL existiert bereits",
        "Wallhaven Queries and Collections (Favorites)": "Wallhaven-Abfragen und -Sammlungen (Favoriten)",
        "New Wikimedia Query": "Neue Wikimedia-Abfrage",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Kategorie-URL, Such-URL oder einfach 'category:Name' eingeben",
        "description too short": "Beschreibung zu kurz",
        "description too long": "Beschreibung zu lang",
        "duplicate query": "Doppelte Abfrage",
        "Add Wikimedia Query": "Wikimedia-Abfrage hinzufügen",
        "Wikimedia Commons Queries": "Wikimedia Commons-Abfragen",
        "Wallhaven Username:": "Wallhaven-Benutzername:",
        "Status: Authorized (Ready to Select)": "Status: Autorisiert (bereit zur Auswahl)",
        "Status: Not Authorized": "Status: Nicht autorisiert",
        "Authorize Google Photos": "Google Fotos autorisieren",
        "Disconnect Authorisation": "Autorisierung aufheben",
        "Success": "Erfolg",
        "Authorized!": "Autorisiert!",
        "Google Photos Integration": "Google Fotos Integration",
        "Status: Checking...": "Status: Überprüfung...",
        "Creating Picker Session...": "Picker-Sitzung wird erstellt...",
        "Please select photos in your browser...": "Bitte wählen Sie Fotos in Ihrem Browser aus...",
        "Waiting for selection (check browser)...": "Warten auf Auswahl (Browser prüfen)...",
        "Retrieving items...": "Elemente werden abgerufen...",
        "Save Collection": "Sammlung speichern",
        "My Collections:": "Meine Sammlungen:",
        "Wallpaper": "Hintergrundbild",
        "Verify Username": "Benutzername verifizieren",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Eines der bedeutendsten Kunstmuseen der Welt, das Ikonen wie Nighthawks und American Gothic beherbergt.",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "Das Kronjuwel von New York City. Von altägyptischen Tempeln bis hin zu modernen Meisterwerken beherbergt das Met 5.000 Jahre der größten kreativen Errungenschaften der Menschheit.",
        "Get a free API key from Pexels.": "Hol dir einen kostenlosen API-Schlüssel von Pexels.",
        "Restricted content requires an API key. Get one here.": "Eingeschränkte Inhalte erfordern einen API-Schlüssel. Hol dir hier einen.",
        "Wikimedia Commons is a media file repository making public domain and": "Wikimedia Commons ist eine Mediensammlung, die gemeinfreie und",
        "freely-licensed educational media content available to everyone.": "frei lizenzierte Bildungsinhalte für alle verfügbar macht.",
        "Donate to Wikimedia": "Spende an Wikimedia",
        "Clear API Key": "API-Schlüssel löschen",
        "Add Pexels Search": "Pexels-Suche hinzufügen",
        "Add Wallhaven URL": "Wallhaven-URL hinzufügen",
        "Verify & Connect": "Verifizieren & Verbinden",
        "Verify & Connect...": "Verifizieren & Verbinden...",
        "Verifying...": "Verifizierung..."
    },
    "es": {
        "(Token Expired)": "(Token expirado)",
        "Downloading %d items...": "Descargando %d elementos...",
        "Error: ": "Error: ",
        "Collection %s (%d items)": "Colección %s (%d elementos)",
        "Enter your Pexels API Key": "Introducir clave API de Pexels",
        "Pexels API Key:": "Clave API de Pexels:",
        "Invalid API Key format (56 characters)": "Formato de clave API no válido (56 caracteres)",
        "New Pexels Query": "Nueva consulta de Pexels",
        "Invalid Pexels URL (search or collection)": "URL de Pexels no válida (búsqueda o colección)",
        "duplicate query: this URL already exists": "Consulta duplicada: esta URL ya existe",
        "Pexels Queries": "Consultas de Pexels",
        "Manage your Pexels image queries here.": "Administre sus consultas de imágenes de Pexels aquí.",
        "API Key required for verification": "Clave API requerida para la verificación",
        "New Image Query": "Nueva consulta de imagen",
        "Invalid wallhaven image query URL pattern": "Patrón de URL de consulta de imagen de Wallhaven no válido",
        "Duplicate query: this URL already exists": "Consulta duplicada: esta URL ya existe",
        "Wallhaven Queries and Collections (Favorites)": "Consultas y colecciones de Wallhaven (Favoritos)",
        "New Wikimedia Query": "Nueva consulta de Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Introducir URL de categoría, URL de búsqueda o simplemente 'category:Nombre'",
        "description too short": "Descripción demasiado corta",
        "description too long": "Descripción demasiado larga",
        "duplicate query": "Consulta duplicada",
        "Add Wikimedia Query": "Añadir consulta de Wikimedia",
        "Wikimedia Commons Queries": "Consultas de Wikimedia Commons",
        "Wallhaven Username:": "Nombre de usuario de Wallhaven:",
        "Status: Authorized (Ready to Select)": "Estado: Autorizado (listo para seleccionar)",
        "Status: Not Authorized": "Estado: No autorizado",
        "Authorize Google Photos": "Autorizar Google Photos",
        "Disconnect Authorisation": "Desconectar autorización",
        "Success": "Éxito",
        "Authorized!": "¡Autorizado!",
        "Google Photos Integration": "Integración con Google Photos",
        "Status: Checking...": "Estado: Comprobando...",
        "Creating Picker Session...": "Creando sesión de selección...",
        "Please select photos in your browser...": "Seleccione fotos en su navegador...",
        "Waiting for selection (check browser)...": "Esperando selección (comprobar navegador)...",
        "Retrieving items...": "Recuperando elementos...",
        "Save Collection": "Guardar colección",
        "My Collections:": "Mis colecciones:",
        "Wallpaper": "Fondo de pantalla",
        "Verify Username": "Verificar nombre de usuario",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Uno de los grandes museos de arte del mundo, que alberga iconos como Nighthawks y American Gothic.",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "La joya de la corona de la ciudad de Nueva York. Desde antiguos templos egipcios hasta obras maestras modernas, el Met alberga 5.000 años de los mayores logros creativos de la humanidad.",
        "Get a free API key from Pexels.": "Obtén una clave API gratuita de Pexels.",
        "Restricted content requires an API key. Get one here.": "El contenido restringido requiere una clave API. Consigue una aquí.",
        "Wikimedia Commons is a media file repository making public domain and": "Wikimedia Commons es un repositorio de archivos multimedia que pone a disposición de todos contenidos de dominio público y",
        "freely-licensed educational media content available to everyone.": "contenidos educativos con licencia libre.",
        "Donate to Wikimedia": "Donar a Wikimedia",
        "Clear API Key": "Borrar clave API",
        "Add Pexels Search": "Añadir búsqueda de Pexels",
        "Add Wallhaven URL": "Añadir URL de Wallhaven",
        "Verify & Connect": "Verificar y conectar",
        "Verify & Connect...": "Verificar y conectar...",
        "Verifying...": "Verificando..."
    },
    "fr": {
        "(Token Expired)": "(Jeton expiré)",
        "Downloading %d items...": "Téléchargement de %d éléments...",
        "Error: ": "Erreur : ",
        "Collection %s (%d items)": "Collection %s (%d éléments)",
        "Enter your Pexels API Key": "Entrez votre clé API Pexels",
        "Pexels API Key:": "Clé API Pexels :",
        "Invalid API Key format (56 characters)": "Format de clé API invalide (56 caractères)",
        "New Pexels Query": "Nouvelle requête Pexels",
        "Invalid Pexels URL (search or collection)": "URL Pexels invalide (recherche ou collection)",
        "duplicate query: this URL already exists": "Requête en double : cette URL existe déjà",
        "Pexels Queries": "Requêtes Pexels",
        "Manage your Pexels image queries here.": "Gérez vos requêtes d'images Pexels ici.",
        "API Key required for verification": "Clé API requise pour la vérification",
        "New Image Query": "Nouvelle requête d'image",
        "Invalid wallhaven image query URL pattern": "Modèle d'URL de requête d'image Wallhaven invalide",
        "Duplicate query: this URL already exists": "Requête en double : cette URL existe déjà",
        "Wallhaven Queries and Collections (Favorites)": "Requêtes et collections Wallhaven (Favoris)",
        "New Wikimedia Query": "Nouvelle requête Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Entrez l'URL de la catégorie, l'URL de recherche ou simplement 'category:Nom'",
        "description too short": "Description trop courte",
        "description too long": "Description trop longue",
        "duplicate query": "Requête en double",
        "Add Wikimedia Query": "Ajouter une requête Wikimedia",
        "Wikimedia Commons Queries": "Requêtes Wikimedia Commons",
        "Wallhaven Username:": "Nom d'utilisateur Wallhaven :",
        "Status: Authorized (Ready to Select)": "État : Autorisé (prêt pour la sélection)",
        "Status: Not Authorized": "État : Non autorisé",
        "Authorize Google Photos": "Autoriser Google Photos",
        "Disconnect Authorisation": "Déconnecter l'autorisation",
        "Success": "Succès",
        "Authorized!": "Autorisé !",
        "Google Photos Integration": "Intégration Google Photos",
        "Status: Checking...": "État : Vérification...",
        "Creating Picker Session...": "Création de la session de sélection...",
        "Please select photos in your browser...": "Veuillez sélectionner des photos dans votre navigateur...",
        "Waiting for selection (check browser)...": "En attente de sélection (vérifier le navigateur)...",
        "Retrieving items...": "Récupération des éléments...",
        "Save Collection": "Sauvegarder la collection",
        "My Collections:": "Mes collections :",
        "Wallpaper": "Fond d'écran",
        "Verify Username": "Vérifier le nom d'utilisateur",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "L'un des plus grands musées d'art au monde, abritant des icônes comme Nighthawks et American Gothic.",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "Le joyau de la couronne de New York. Des anciens temples égyptiens aux chefs-d'œuvre modernes, le Met abrite 5 000 ans des plus grandes réalisations créatives de l'humanité.",
        "Get a free API key from Pexels.": "Obtenez une clé API gratuite de Pexels.",
        "Restricted content requires an API key. Get one here.": "Le contenu restreint nécessite une clé API. Obtenez-en une ici.",
        "Wikimedia Commons is a media file repository making public domain and": "Wikimedia Commons est une médiathèque de fichiers qui met à la disposition de tous des contenus du domaine public et",
        "freely-licensed educational media content available to everyone.": "des contenus éducatifs sous licence libre.",
        "Donate to Wikimedia": "Faire un don à Wikimedia",
        "Clear API Key": "Effacer la clé API",
        "Add Pexels Search": "Ajouter une recherche Pexels",
        "Add Wallhaven URL": "Ajouter une URL Wallhaven",
        "Verify & Connect": "Vérifier et connecter",
        "Verify & Connect...": "Vérifier et connecter...",
        "Verifying...": "Vérification..."
    },
    "it": {
        "(Token Expired)": "(Token scaduto)",
        "Downloading %d items...": "Download di %d elementi...",
        "Error: ": "Errore: ",
        "Collection %s (%d items)": "Collezione %s (% d elementi)",
        "Enter your Pexels API Key": "Inserisci la chiave API di Pexels",
        "Pexels API Key:": "Chiave API di Pexels:",
        "Invalid API Key format (56 characters)": "Formato chiave API non valido (56 caratteri)",
        "New Pexels Query": "Nuova query Pexels",
        "Invalid Pexels URL (search or collection)": "URL Pexels non valido (ricerca o collezione)",
        "duplicate query: this URL already exists": "Query duplicata: questo URL esiste già",
        "Pexels Queries": "Query Pexels",
        "Manage your Pexels image queries here.": "Gestisci qui le tue query di immagini Pexels.",
        "API Key required for verification": "Chiave API richiesta per la verifica",
        "New Image Query": "Nuova query immagine",
        "Invalid wallhaven image query URL pattern": "Modello URL query immagine Wallhaven non valido",
        "Duplicate query: this URL already exists": "Query duplicata: questo URL esiste già",
        "Wallhaven Queries and Collections (Favorites)": "Query e collezioni di Wallhaven (Preferiti)",
        "New Wikimedia Query": "Nuova query Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Inserisci URL categoria, URL ricerca o semplicemente 'category:Nome'",
        "description too short": "Descrizione troppo breve",
        "description too long": "Descrizione troppo lunga",
        "duplicate query": "Query duplicata",
        "Add Wikimedia Query": "Aggiungi query Wikimedia",
        "Wikimedia Commons Queries": "Query di Wikimedia Commons",
        "Wallhaven Username:": "Nome utente Wallhaven:",
        "Status: Authorized (Ready to Select)": "Stato: Autorizzato (pronto per la selezione)",
        "Status: Not Authorized": "Stato: Non autorizzato",
        "Authorize Google Photos": "Autorizza Google Photos",
        "Disconnect Authorisation": "Disconnetti autorizzazione",
        "Success": "Successo",
        "Authorized!": "Autorizzato!",
        "Google Photos Integration": "Integrazione con Google Photos",
        "Status: Checking...": "Stato: Verifica in corso...",
        "Creating Picker Session...": "Creazione sessione di selezione...",
        "Please select photos in your browser...": "Seleziona le foto nel tuo browser...",
        "Waiting for selection (check browser)...": "In attesa di selezione (controlla il browser)...",
        "Retrieving items...": "Recupero elementi...",
        "Save Collection": "Salva collezione",
        "My Collections:": "Le mie collezioni:",
        "Wallpaper": "Sfondo",
        "Verify Username": "Verifica nome utente",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Uno dei più grandi musei d'arte del mondo, che ospita icone come Nighthawks e American Gothic.",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "Il gioiello della corona di New York City. Daglie antichi templi egizi ai capolavori moderni, il Met ospita 5.000 anni delle più grandi conquiste creative dell'umanità.",
        "Get a free API key from Pexels.": "Ottieni una chiave API gratuita da Pexels.",
        "Restricted content requires an API key. Get one here.": "I contenuti limitati richiedono una chiave API. Ottienine una qui.",
        "Wikimedia Commons is a media file repository making public domain and": "Wikimedia Commons è un archivio di file multimediali che mette a disposizione di tutti contenuti di pubblico dominio e",
        "freely-licensed educational media content available to everyone.": "contenuti multimediali educativi con licenza libera.",
        "Donate to Wikimedia": "Dona a Wikimedia",
        "Clear API Key": "Cancella chiave API",
        "Add Pexels Search": "Aggiungi ricerca Pexels",
        "Add Wallhaven URL": "Aggiungi URL Wallhaven",
        "Verify & Connect": "Verifica e connetti",
        "Verify & Connect...": "Verifica e connetti...",
        "Verifying...": "Verifica in corso..."
    },
    "ja": {
        "(Token Expired)": "(トークンの期限切れ)",
        "Downloading %d items...": "%d 個のアイテムをダウンロード中...",
        "Error: ": "エラー: ",
        "Collection %s (%d items)": "コレクション %s (%d 個のアイテム)",
        "Enter your Pexels API Key": "Pexels API キーを入力してください",
        "Pexels API Key:": "Pexels API キー:",
        "Invalid API Key format (56 characters)": "API キー形式が無効です (56 文字)",
        "New Pexels Query": "新しい Pexels クエリ",
        "Invalid Pexels URL (search or collection)": "無効な Pexels URL (検索またはコレクション)",
        "duplicate query: this URL already exists": "重複したクエリ: この URL は既に存在します",
        "Pexels Queries": "Pexels クエリ",
        "Manage your Pexels image queries here.": "ここで Pexels 画像クエリを管理します。",
        "API Key required for verification": "検証には API キーが必要です",
        "New Image Query": "新しい画像クエリ",
        "Invalid wallhaven image query URL pattern": "無効な Wallhaven 画像クエリ URL パターン",
        "Duplicate query: this URL already exists": "重複したクエリ: この URL は既に存在します",
        "Wallhaven Queries and Collections (Favorites)": "Wallhaven クエリとコレクション (お気に入り)",
        "New Wikimedia Query": "新しい Wikimedia クエリ",
        "Enter Category URL, Search URL, or plain 'category:Name'": "カテゴリ URL、検索 URL、または単に 'category:名前' を入力してください",
        "description too short": "説明が短すぎます",
        "description too long": "説明が長すぎます",
        "duplicate query": "重複したクエリ",
        "Add Wikimedia Query": "Wikimedia クエリを追加",
        "Wikimedia Commons Queries": "Wikimedia Commons クエリ",
        "Wallhaven Username:": "Wallhaven ユーザー名:",
        "Status: Authorized (Ready to Select)": "ステータス: 承認済み (選択可能)",
        "Status: Not Authorized": "ステータス: 未承認",
        "Authorize Google Photos": "Google フォトを承認",
        "Disconnect Authorisation": "承認を解除",
        "Success": "成功",
        "Authorized!": "承認されました！",
        "Google Photos Integration": "Google フォト連携",
        "Status: Checking...": "ステータス: 確認中...",
        "Creating Picker Session...": "ピッカーセッション作成中...",
        "Please select photos in your browser...": "ブラウザで写真を選択してください...",
        "Waiting for selection (check browser)...": "選択待ちです (ブラウザを確認してください)...",
        "Retrieving items...": "アイテムを取得中...",
        "Save Collection": "コレクションを保存",
        "My Collections:": "マイコレクション:",
        "Wallpaper": "壁紙",
        "Verify Username": "ユーザー名を検証",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "ナイトホークスやアメリカン・ゴシックなどの象徴的な作品を収蔵する、世界有数の美術館です。",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "ニューヨークの至宝。古代エジプトの神殿から現代の傑作まで、メトロポリタン美術館には人類の 5,000 年にわたる偉大な創造的功績が収蔵されています。",
        "Get a free API key from Pexels.": "Pexels から無料の API キーを取得します。",
        "Restricted content requires an API key. Get one here.": "制限されたコンテンツには API キーが必要です。こちらから取得してください。",
        "Wikimedia Commons is a media file repository making public domain and": "ウィキメディア・コモンズは、パブリックドメインや自由にライセンスされた",
        "freely-licensed educational media content available to everyone.": "教育用メディアコンテンツを誰もが利用できるようにするメディアファイルリポジトリです。",
        "Donate to Wikimedia": "ウィキメディアに寄付する",
        "Clear API Key": "API キーを消去",
        "Add Pexels Search": "Pexels 検索を追加",
        "Add Wallhaven URL": "Wallhaven URL を追加",
        "Verify & Connect": "検証して接続",
        "Verify & Connect...": "検証して接続中...",
        "Verifying...": "検証中..."
    },
    "pt": {
        "(Token Expired)": "(Token expirado)",
        "Downloading %d items...": "Baixando %d itens...",
        "Error: ": "Erro: ",
        "Collection %s (%d items)": "Coleção %s (%d itens)",
        "Enter your Pexels API Key": "Digite sua chave API do Pexels",
        "Pexels API Key:": "Chave API do Pexels:",
        "Invalid API Key format (56 characters)": "Formato de chave API inválido (56 caracteres)",
        "New Pexels Query": "Nova consulta do Pexels",
        "Invalid Pexels URL (search or collection)": "URL do Pexels inválida (pesquisa ou coleção)",
        "duplicate query: this URL already exists": "Consulta duplicada: este URL já existe",
        "Pexels Queries": "Consultas do Pexels",
        "Manage your Pexels image queries here.": "Gerencie suas consultas de imagens do Pexels aqui.",
        "API Key required for verification": "Chave API necessária para verificação",
        "New Image Query": "Nova consulta de imagem",
        "Invalid wallhaven image query URL pattern": "Padrão de URL de consulta de imagem do Wallhaven inválido",
        "Duplicate query: this URL already exists": "Consulta duplicada: este URL já existe",
        "Wallhaven Queries and Collections (Favorites)": "Consultas e Coleções do Wallhaven (Favoritos)",
        "New Wikimedia Query": "Nova consulta do Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Digite o URL da categoria, o URL de pesquisa ou simplesmente 'category:Nome'",
        "description too short": "Descrição muito curta",
        "description too long": "Descrição muito longa",
        "duplicate query": "Consulta duplicada",
        "Add Wikimedia Query": "Adicionar consulta do Wikimedia",
        "Wikimedia Commons Queries": "Consultas do Wikimedia Commons",
        "Wallhaven Username:": "Nome de usuário do Wallhaven:",
        "Status: Authorized (Ready to Select)": "Status: Autorizado (pronto para selecionar)",
        "Status: Not Authorized": "Status: Não autorizado",
        "Authorize Google Photos": "Autorizar Google Photos",
        "Disconnect Authorisation": "Desconectar autorização",
        "Success": "Sucesso",
        "Authorized!": "Autorizado!",
        "Google Photos Integration": "Integração com Google Photos",
        "Status: Checking...": "Status: Verificando...",
        "Creating Picker Session...": "Criando sessão de seleção...",
        "Please select photos in your browser...": "Selecione as fotos no seu navegador...",
        "Waiting for selection (check browser)...": "Aguardando seleção (verifique o navegador)...",
        "Retrieving items...": "Recuperando itens...",
        "Save Collection": "Salvar coleção",
        "My Collections:": "Minhas coleções:",
        "Wallpaper": "Papel de Parede",
        "Verify Username": "Verificar nome de usuário",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Um dos maiores museus de arte do mundo, abrigando ícones como Nighthawks e American Gothic.",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "A joia da coroa da cidade de Nova York. De antigos templos egípcios a obras-primas modernas, o Met abriga 5.000 anos das maiores conquistas criativas da humanidade.",
        "Get a free API key from Pexels.": "Obtenha uma chave API gratuita do Pexels.",
        "Restricted content requires an API key. Get one here.": "Conteúdo restrito requer uma chave API. Consiga uma aqui.",
        "Wikimedia Commons is a media file repository making public domain and": "O Wikimedia Commons é um repositório de arquivos de mídia que disponibiliza conteúdo de domínio público e",
        "freely-licensed educational media content available to everyone.": "conteúdo de mídia educacional com licença livre para todos.",
        "Donate to Wikimedia": "Doe para o Wikimedia",
        "Clear API Key": "Limpar chave API",
        "Add Pexels Search": "Adicionar busca do Pexels",
        "Add Wallhaven URL": "Adicionar URL do Wallhaven",
        "Verify & Connect": "Verificar e conectar",
        "Verify & Connect...": "Verificar e conectar...",
        "Verifying...": "Verificando..."
    },
    "ru": {
        "(Token Expired)": "(Токен истек)",
        "Downloading %d items...": "Загрузка %d элементов...",
        "Error: ": "Ошибка: ",
        "Collection %s (%d items)": "Коллекция %s (%d элементов)",
        "Enter your Pexels API Key": "Введите ключ API Pexels",
        "Pexels API Key:": "Ключ API Pexels:",
        "Invalid API Key format (56 characters)": "Неверный формат ключа API (56 символов)",
        "New Pexels Query": "Новый запрос Pexels",
        "Invalid Pexels URL (search or collection)": "Неверный URL Pexels (поиск или коллекция)",
        "duplicate query: this URL already exists": "Дубликат запроса: этот URL уже существует",
        "Pexels Queries": "Запросы Pexels",
        "Manage your Pexels image queries here.": "Управляйте запросами изображений Pexels здесь.",
        "API Key required for verification": "Для проверки требуется ключ API",
        "New Image Query": "Новый запрос изображения",
        "Invalid wallhaven image query URL pattern": "Неверный шаблон URL запроса изображения Wallhaven",
        "Duplicate query: this URL already exists": "Дубликат запроса: этот URL уже существует",
        "Wallhaven Queries and Collections (Favorites)": "Запросы и коллекции Wallhaven (Избранное)",
        "New Wikimedia Query": "Новый запрос Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Введите URL категории, URL поиска или просто 'category:Имя'",
        "description too short": "Описание слишком короткое",
        "description too long": "Описание слишком длинное",
        "duplicate query": "Дубликат запроса",
        "Add Wikimedia Query": "Добавить запрос Wikimedia",
        "Wikimedia Commons Queries": "Запросы Wikimedia Commons",
        "Wallhaven Username:": "Имя пользователя Wallhaven:",
        "Status: Authorized (Ready to Select)": "Статус: Авторизовано (готово к выбору)",
        "Status: Not Authorized": "Статус: Не авторизовано",
        "Authorize Google Photos": "Авторизовать Google Фото",
        "Disconnect Authorisation": "Отозвать авторизацию",
        "Success": "Успех",
        "Authorized!": "Авторизовано!",
        "Google Photos Integration": "Интеграция с Google Фото",
        "Status: Checking...": "Статус: Проверка...",
        "Creating Picker Session...": "Создание сессии выбора...",
        "Please select photos in your browser...": "Пожалуйста, выберите фотографии в браузере...",
        "Waiting for selection (check browser)...": "Ожидание выбора (проверьте браузер)...",
        "Retrieving items...": "Получение элементов...",
        "Save Collection": "Сохранить коллекцию",
        "My Collections:": "Мои коллекции:",
        "Wallpaper": "Обои",
        "Verify Username": "Проверить имя пользователя",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Один из величайших художественных музеев мира, где хранятся такие иконы, как «Полуночники» и «Американская готика».",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "Жемчужина Нью-Йорка. От древнеегипетских храмов до современных шедевров, Метрополитен-музей хранит в себе 5000 лет величайших творческих достижений человечества.",
        "Get a free API key from Pexels.": "Получите бесплатный ключ API от Pexels.",
        "Restricted content requires an API key. Get one here.": "Для доступа к ограниченному контенту требуется ключ API. Получите его здесь.",
        "Wikimedia Commons is a media file repository making public domain and": "Викисклад — это хранилище медиафайлов, обеспечивающее доступность для всех",
        "freely-licensed educational media content available to everyone.": "общественного достояния и свободно лицензируемого образовательного медиаконтента.",
        "Donate to Wikimedia": "Пожертвовать Викимедиа",
        "Clear API Key": "Очистить ключ API",
        "Add Pexels Search": "Добавить поиск Pexels",
        "Add Wallhaven URL": "Добавить URL Wallhaven",
        "Verify & Connect": "Проверить и подключить",
        "Verify & Connect...": "Проверка и подключение...",
        "Verifying...": "Проверка..."
    },
    "uk": {
        "(Token Expired)": "(Токен закінчився)",
        "Downloading %d items...": "Завантаження %d елементів...",
        "Error: ": "Помилка: ",
        "Collection %s (%d items)": "Колекція %s (%d елементів)",
        "Enter your Pexels API Key": "Введіть ключ API Pexels",
        "Pexels API Key:": "Ключ API Pexels:",
        "Invalid API Key format (56 characters)": "Невірний формат ключа API (56 символів)",
        "New Pexels Query": "Новий запит Pexels",
        "Invalid Pexels URL (search or collection)": "Невірна URL-адреса Pexels (пошук або колекція)",
        "duplicate query: this URL already exists": "Дублікат запиту: ця URL-адреса вже існує",
        "Pexels Queries": "Запити Pexels",
        "Manage your Pexels image queries here.": "Керуйте запитами зображень Pexels тут.",
        "API Key required for verification": "Для перевірки потрібен ключ API",
        "New Image Query": "Новий запит зображення",
        "Invalid wallhaven image query URL pattern": "Невірний шаблон URL-адреси запиту зображення Wallhaven",
        "Duplicate query: this URL already exists": "Дублікат запиту: ця URL-адреса вже існує",
        "Wallhaven Queries and Collections (Favorites)": "Запити та колекції Wallhaven (Вибране)",
        "New Wikimedia Query": "Новий запит Wikimedia",
        "Enter Category URL, Search URL, or plain 'category:Name'": "Введіть URL-адресу категорії, URL-адресу пошуку або просто 'category:Ім'я'",
        "description too short": "Опис занадто короткий",
        "description too long": "Опис занадто довгий",
        "duplicate query": "Дублікат запиту",
        "Add Wikimedia Query": "Додати запит Wikimedia",
        "Wikimedia Commons Queries": "Запити Wikimedia Commons",
        "Wallhaven Username:": "Ім'я користувача Wallhaven:",
        "Status: Authorized (Ready to Select)": "Статус: Авторизовано (готове до вибору)",
        "Status: Not Authorized": "Статус: Не авторизовано",
        "Authorize Google Photos": "Авторизувати Google Фото",
        "Disconnect Authorisation": "Відкликати авторизацію",
        "Success": "Успіх",
        "Authorized!": "Авторизовано!",
        "Google Photos Integration": "Інтеграція з Google Фото",
        "Status: Checking...": "Статус: Перевірка...",
        "Creating Picker Session...": "Створення сесії вибору...",
        "Please select photos in your browser...": "Будь ласка, виберіть фотографії у браузері...",
        "Waiting for selection (check browser)...": "Очікування вибору (перевірте браузер)...",
        "Retrieving items...": "Отримання елементів...",
        "Save Collection": "Зберегти колекцію",
        "My Collections:": "Мої колекції:",
        "Wallpaper": "Шпалери",
        "Verify Username": "Перевірити ім'я користувача",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "Один із найвизначніших художніх музеїв світу, де зберігаються такі ікони, як «Опівнічники» та «Американська готика».",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "Перлина Нью-Йорка. Від давньоєгипетських храмів до сучасних шедеврів, Метрополітен-музей зберігає 5000 років найвидатніших творчих досягнень людства.",
        "Get a free API key from Pexels.": "Отримайте безкоштовний ключ API від Pexels.",
        "Restricted content requires an API key. Get one here.": "Для доступу до обмеженого вмісту потрібен ключ API. Отримайте його тут.",
        "Wikimedia Commons is a media file repository making public domain and": "Вікісховище — це сховище медіафайлів, що забезпечує доступність для всіх",
        "freely-licensed educational media content available to everyone.": "суспільного надбання та вільно ліцензованого освітнього медіаконтенту.",
        "Donate to Wikimedia": "Пожертувати Вікімедіа",
        "Clear API Key": "Очистити ключ API",
        "Add Pexels Search": "Додати пошук Pexels",
        "Add Wallhaven URL": "Додати URL Wallhaven",
        "Verify & Connect": "Перевірити та підключити",
        "Verify & Connect...": "Перевірка та підключення...",
        "Verifying...": "Перевірка..."
    },
    "zh": {
        "(Token Expired)": "(令牌已过期)",
        "Downloading %d items...": "正在下载 %d 个项目...",
        "Error: ": "错误: ",
        "Collection %s (%d items)": "收藏集 %s (%d 个项目)",
        "Enter your Pexels API Key": "输入您的 Pexels API 密钥",
        "Pexels API Key:": "Pexels API 密钥:",
        "Invalid API Key format (56 characters)": "API 密钥格式无效 (56 个字符)",
        "New Pexels Query": "新建 Pexels 查询",
        "Invalid Pexels URL (search or collection)": "无效的 Pexels URL (搜索或收藏集)",
        "duplicate query: this URL already exists": "重复查询: 此 URL 已存在",
        "Pexels Queries": "Pexels 查询",
        "Manage your Pexels image queries here.": "在此管理您的 Pexels 图片查询。",
        "API Key required for verification": "验证需要 API 密钥",
        "New Image Query": "新建图片查询",
        "Invalid wallhaven image query URL pattern": "无效的 Wallhaven 图片查询 URL 模式",
        "Duplicate query: this URL already exists": "重复查询: 此 URL 已存在",
        "Wallhaven Queries and Collections (Favorites)": "Wallhaven 查询和收藏集 (收藏夹)",
        "New Wikimedia Query": "新建 Wikimedia 查询",
        "Enter Category URL, Search URL, or plain 'category:Name'": "输入类别 URL、搜索 URL 或简称 'category:名称'",
        "description too short": "描述太短",
        "description too long": "描述太长",
        "duplicate query": "重复查询",
        "Add Wikimedia Query": "添加 Wikimedia 查询",
        "Wikimedia Commons Queries": "Wikimedia Commons 查询",
        "Wallhaven Username:": "Wallhaven 用户名:",
        "Status: Authorized (Ready to Select)": "状态: 已授权 (准备选择)",
        "Status: Not Authorized": "状态: 未授权",
        "Authorize Google Photos": "授权 Google 相册",
        "Disconnect Authorisation": "断开授权",
        "Success": "成功",
        "Authorized!": "已授权！",
        "Google Photos Integration": "Google 相册集成",
        "Status: Checking...": "状态: 正在检查...",
        "Creating Picker Session...": "正在创建选择器会话...",
        "Please select photos in your browser...": "请在浏览器中选择照片...",
        "Waiting for selection (check browser)...": "等待选择 (请检查浏览器)...",
        "Retrieving items...": "正在获取项目...",
        "Save Collection": "保存收藏集",
        "My Collections:": "我的收藏集:",
        "Wallpaper": "壁纸",
        "Verify Username": "验证用户名",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "世界顶尖的艺术博物馆之一，馆藏包括《夜游者》和《美国哥特式》等图标性作品。",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "纽约市的璀璨明珠。从古埃及神庙到现代杰作，大都会艺术博物馆收藏了人类 5,000 年来最伟大的创造力成就。",
        "Get a free API key from Pexels.": "从 Pexels 获取免费的 API 密钥。",
        "Restricted content requires an API key. Get one here.": "受限内容需要 API 密钥。点击此处获取。",
        "Wikimedia Commons is a media file repository making public domain and": "维基共享资源是一个媒体文件库，向所有人提供公共领域和",
        "freely-licensed educational media content available to everyone.": "免费授权的教育媒体内容。",
        "Donate to Wikimedia": "向维基媒体捐款",
        "Clear API Key": "清除 API 密钥",
        "Add Pexels Search": "添加 Pexels 搜索",
        "Add Wallhaven URL": "添加 Wallhaven URL",
        "Verify & Connect": "验证并连接",
        "Verify & Connect...": "正在验证并连接...",
        "Verifying...": "正在验证..."
    },
    "zh-Hant": {
        "(Token Expired)": "(權杖已過期)",
        "Downloading %d items...": "正在下載 %d 個項目...",
        "Error: ": "錯誤: ",
        "Collection %s (%d items)": "收藏集 %s (%d 個項目)",
        "Enter your Pexels API Key": "輸入您的 Pexels API 金鑰",
        "Pexels API Key:": "Pexels API 金鑰:",
        "Invalid API Key format (56 characters)": "API 金鑰格式無效 (56 個字元)",
        "New Pexels Query": "新建 Pexels 查詢",
        "Invalid Pexels URL (search or collection)": "無效的 Pexels URL (搜尋或收藏集)",
        "duplicate query: this URL already exists": "重複查詢: 此 URL 已存在",
        "Pexels Queries": "Pexels 查詢",
        "Manage your Pexels image queries here.": "在此管理您的 Pexels 圖片查詢。",
        "API Key required for verification": "驗證需要 API 金鑰",
        "New Image Query": "新建圖片查詢",
        "Invalid wallhaven image query URL pattern": "無效的 Wallhaven 圖片查詢 URL 模式",
        "Duplicate query: this URL already exists": "重複查詢: 此 URL 已存在",
        "Wallhaven Queries and Collections (Favorites)": "Wallhaven 查詢和收藏集 (收藏夾)",
        "New Wikimedia Query": "新建 Wikimedia 查詢",
        "Enter Category URL, Search URL, or plain 'category:Name'": "輸入類別 URL、搜尋 URL 或簡稱 'category:名稱'",
        "description too short": "描述太短",
        "description too long": "描述太長",
        "duplicate query": "重複查詢",
        "Add Wikimedia Query": "新增 Wikimedia 查詢",
        "Wikimedia Commons Queries": "Wikimedia Commons 查詢",
        "Wallhaven Username:": "Wallhaven 使用者名稱:",
        "Status: Authorized (Ready to Select)": "狀態: 已授權 (準備選擇)",
        "Status: Not Authorized": "狀態: 未授權",
        "Authorize Google Photos": "授權 Google 相簿",
        "Disconnect Authorisation": "斷開授權",
        "Success": "成功",
        "Authorized!": "已授權！",
        "Google Photos Integration": "Google 相簿整合",
        "Status: Checking...": "狀態: 正在檢查...",
        "Creating Picker Session...": "正在建立選擇器工作階段...",
        "請在瀏覽器中選擇照片...": "請在瀏覽器中選擇照片...",
        "Waiting for selection (check browser)...": "等待選擇 (請檢查瀏覽器)...",
        "Retrieving items...": "正在取得項目...",
        "Save Collection": "儲存收藏集",
        "My Collections:": "我的收藏集:",
        "Wallpaper": "桌布",
        "Verify Username": "驗證使用者名稱",
        "One of the world's great art museums, housing icons like Nighthawks and American Gothic.": "世界頂尖的藝術博物館之一，館藏包括《夜游者》和《美國哥特式》等圖標性作品。",
        "The crown jewel of New York City. From ancient Egyptian temples to modern masterpieces, The Met houses 5,000 years of humanity's greatest creative achievements.": "紐約市的璀璨明珠。從古埃及神廟到現代傑作，大都會藝術博物館收藏了人類 5,000 年來最偉大的創造力成就。",
        "Get a free API key from Pexels.": "從 Pexels 取得免費的 API 金鑰。",
        "Restricted content requires an API key. Get one here.": "受限內容需要 API 金鑰。點擊此處取得。",
        "Wikimedia Commons is a media file repository making public domain and": "維基共享資源是一個媒體文件庫，向所有人提供公共領域和",
        "freely-licensed educational media content available to everyone.": "免費授權的教育媒體內容。",
        "Donate to Wikimedia": "向維基媒體捐款",
        "Clear API Key": "清除 API 金鑰",
        "Add Pexels Search": "新增 Pexels 搜尋",
        "Add Wallhaven URL": "新增 Wallhaven URL",
        "Verify & Connect": "驗證並連接",
        "Verify & Connect...": "正在驗證並連接...",
        "Verifying...": "正在驗證..."
    }
}

translations_dir = "pkg/i18n/translations"

def batch_translate():
    for lang, terms in translations.items():
        filepath = os.path.join(translations_dir, f"{lang}.json")
        if not os.path.exists(filepath):
            print(f"Skipping {lang}, file not found.")
            continue
            
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        updated = False
        for key, val in terms.items():
            if key in data:
                # Update if it's the same as the key (English fallback) OR if we want to force update
                if data[key] == key:
                    data[key] = val
                    updated = True
                # Force update for specific keys reported as unlocalized
                elif key in ["Clear API Key", "Add Pexels Search", "Add Wallhaven URL", "Verify & Connect", "Verify Username"]:
                    data[key] = val
                    updated = True
                # Special cases for long strings
                elif len(key) > 50 or "Donate" in key or "API key" in key:
                    data[key] = val
                    updated = True
            else:
                data[key] = val
                updated = True
                
        if updated:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Updated {lang}.json")
        else:
            print(f"No updates needed for {lang}.json")

if __name__ == "__main__":
    batch_translate()
