package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Since go generate sets CWD to the directory of the file,
	// we need to step out to the project root.
	// cmd/spice -> . (root) is ../../
	root := "../../"
	providersDir := filepath.Join(root, "pkg/wallpaper/providers")
	outputFile := filepath.Join(root, "cmd/spice/zz_generated_providers.go")

	entries, err := os.ReadDir(providersDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read providers dir at %s: %v\n", providersDir, err)
		os.Exit(1)
	}

	var packages []string
	for _, entry := range entries {
		if entry.IsDir() {
			// Check for .disabled marker file
			disabledMarker := filepath.Join(providersDir, entry.Name(), ".disabled")
			if _, err := os.Stat(disabledMarker); err == nil {
				fmt.Printf("Skipping disabled provider: %s\n", entry.Name())
				continue
			}
			packages = append(packages, entry.Name())
		}
	}
	sort.Strings(packages)

	var sb strings.Builder
	sb.WriteString("// Code generated by gen_providers; DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\n")
	sb.WriteString("import (\n")
	for _, pkg := range packages {
		sb.WriteString(fmt.Sprintf("\t_ \"github.com/dixieflatline76/Spice/pkg/wallpaper/providers/%s\"\n", pkg))
	}
	sb.WriteString(")\n")

	// Ensure the parent directory exists (though cmd/spice definitely does)
	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output dir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d providers\n", outputFile, len(packages))
}
