package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	// Since go generate sets CWD to the directory of the file (cmd/spice),
	// we need to step out to the project root.
	// cmd/spice -> . (root) is ../../
	root := "../../"
	providersDir := filepath.Join(root, "pkg/wallpaper/providers")
	docsDir := filepath.Join(root, "docs/collections")
	outputFile := filepath.Join(root, "cmd/spice/zz_generated_providers.go")
	mapOutputFile := filepath.Join(root, "pkg/curation/zz_generated_provider_map.go")

	entries, err := os.ReadDir(providersDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read providers dir at %s: %v\n", providersDir, err)
		os.Exit(1)
	}

	providerNameToFilename := make(map[string]string)
	providerNameRegex := regexp.MustCompile(`ProviderName\s*=\s*"([^"]+)"`)
	var packages []string

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		pkgName := entry.Name()
		disabledMarker := filepath.Join(providersDir, pkgName, ".disabled")
		if _, err := os.Stat(disabledMarker); err == nil {
			fmt.Printf("Skipping disabled provider: %s\n", pkgName)
			continue
		}
		packages = append(packages, pkgName)

		// Check if this provider has an associated JSON file in docs/collections/
		jsonFilename := pkgName + ".json"
		jsonPath := filepath.Join(docsDir, jsonFilename)
		if _, err := os.Stat(jsonPath); err == nil {
			// Find the ProviderName constant in the package
			files, _ := filepath.Glob(filepath.Join(providersDir, pkgName, "*.go"))
			foundProviderName := ""
			for _, file := range files {
				content, err := os.ReadFile(file)
				if err != nil {
					continue
				}
				matches := providerNameRegex.FindStringSubmatch(string(content))
				if len(matches) > 1 {
					foundProviderName = matches[1]
					break
				}
			}
			if foundProviderName != "" {
				providerNameToFilename[foundProviderName] = jsonFilename
			} else {
				fmt.Printf("Warning: Found JSON %s but could not find ProviderName constant in package %s\n", jsonFilename, pkgName)
			}
		}
	}
	sort.Strings(packages)

	// 1. Generate zz_generated_providers.go
	var sb strings.Builder
	sb.WriteString("// Code generated by gen_providers; DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\n")
	sb.WriteString("import (\n")
	for _, pkg := range packages {
		sb.WriteString(fmt.Sprintf("\t_ \"github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/%s\"\n", pkg))
	}
	sb.WriteString(")\n")

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputFile, []byte(sb.String()), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
		os.Exit(1)
	}

	// 2. Generate zz_generated_provider_map.go
	var mapSb strings.Builder
	mapSb.WriteString("// Code generated by gen_providers; DO NOT EDIT.\n\n")
	mapSb.WriteString("package curation\n\n")
	mapSb.WriteString("// ProviderIDToFilename maps the unique Provider ID strings (e.g. \"MetMuseum\")\n")
	mapSb.WriteString("// to their corresponding curated JSON filenames in docs/collections/ (e.g. \"metmuseum.json\")\n")
	mapSb.WriteString("var ProviderIDToFilename = map[string]string{\n")

	// Sort map keys for deterministic output
	var pNames []string
	for k := range providerNameToFilename {
		pNames = append(pNames, k)
	}
	sort.Strings(pNames)

	for _, pName := range pNames {
		mapSb.WriteString(fmt.Sprintf("\t%q: %q,\n", pName, providerNameToFilename[pName]))
	}
	mapSb.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(mapOutputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create map output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(mapOutputFile, []byte(mapSb.String()), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write map output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d providers\n", outputFile, len(packages))
	fmt.Printf("Generated %s with %d mappings\n", mapOutputFile, len(providerNameToFilename))
}
