// Code generated by gen_providers; DO NOT EDIT.

package main

import (
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/artic"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/favorites"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/googlephotos"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/localfolder"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/metmuseum"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/pexels"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/wallhaven"
	_ "github.com/dixieflatline76/Spice/v2/pkg/wallpaper/providers/wikimedia"
)
